### ISSUE TITLE
Add MidnightControls

### ISSUE THREAD

**Issue by emifloofy** [HerrahStrings/packwiz-packs#20]
I believe that MidnightControls could be a great addition, as it would let people with motion disabilities and people who are just plain used to playing with a controller play this modpack OOTB.

Not sure if MidnightControlsExtra would be necessary, as the Reacharound mod is already present in the pack, and I don't believe the other features are all that important.

**Comment by sleepingdragoninn** [comment]
We definitely recommend players install midnight controls if they're planning to use a controller and set up the binds however works for them - I'm also happy for said players to submit their bind setups in this thread to be shipped with the pack! (if you can pull off getting stance swapping / WTHIT etc in)

In terms of actually including the mod in the pack by default, we'll probably do it when we swap from FTB quests to a quest mod that has keyboard control - that'll probably be in 1.20. We just wanna make sure we're packing in stuff that's up to TQuilt polish standards.

**Comment by sleepingdragoninn** [comment]
For TQuilt 1.20 we now recommend controlify https://modrinth.com/mod/controlify which utilizes the keyboard navigation added in 1.19.4

**Comment by sleepingdragoninn** [comment]
going to close this as the pack description has an explicit recommendation
