### ISSUE TITLE
switch from mcwifipnp to World Host

### ISSUE THREAD

**Issue by aquifolly** [HerrahStrings/packwiz-packs#21]
I find that mcwifipnp requires that I change my network settings, and World Host works ootb
https://modrinth.com/mod/world-host

**Comment by sleepingdragoninn** [comment]
That mod uses a third party listen server out of any user's control, not NAT punchthrough. if it works for you, definitely use it in your own instance.

**Comment by sisby-folk** [comment]
*mod
