### ISSUE TITLE
Project Odyssey

### ISSUE THREAD

**Issue by aquifolly** [HerrahStrings/packwiz-packs#22]
what would you think about switching from the FTB mods to Project Odyssey?
see: https://floss.social/@modrinth/110522805928116280

**Comment by sleepingdragoninn** [comment]
on the cards! Heracles specifically. We talked to the devs pre release about mod features and basically we're planning to migrate our quest trees to Heracles in TQuilt 1.20

In terms of when - I'd say TQuilt 1.20 will probably be viable sometime after blanketcon - gotta wait out those mod updates.

**Comment by sleepingdragoninn** [comment]
![image](https://github.com/sisby-folk/mc-packs/assets/55819817/94fb65f3-70d7-400e-8011-2831a92c2123)

slowly getting there, but it's not parsing everything yet.

**Comment by aquifolly** [comment]
may i ask what font that is?

**Comment by sleepingdragoninn** [comment]
unsanded!

**Comment by aquifolly** [comment]
ah, the one that una made
looks clean

**Comment by sleepingdragoninn** [comment]
Closing this one now that the tquilt 1.20 edge versions are up and working

![javaw_QxT0qbjNKf](https://github.com/sisby-folk/tinkerers-quilt/assets/55819817/71b4179e-cb6a-42ce-a3ab-ed870b83c6db)
