### ISSUE TITLE
Can't find quests anywhere 

### ISSUE THREAD

**Issue by wisewight** [HerrahStrings/packwiz-packs#24]
Cant find a way to open the quest menu

**Comment by sleepingdragoninn** [comment]
check the changelog [here](https://modrinth.com/modpack/tinkerers-quilt/version/4.0.1), the quest mod is a manual download for licensing reasons.

**Comment by AlkyoneAoide** [comment]
Would it be possible to prompt for FTB library/teams/quests similarly to other modpacks?  It feels preferable as a player, especially one playing for the quests, though I understand if it isn't doable.

![prismlauncher](https://github.com/sisby-folk/mc-packs/assets/42421590/cf15d7ba-5df5-401a-a520-202802ea5833)

![atlauncher-1](https://github.com/sisby-folk/mc-packs/assets/42421590/3b4b5c7d-9ff9-4a22-8eed-033013007716)

![atlauncher-2](https://github.com/sisby-folk/mc-packs/assets/42421590/918fb339-0291-49a8-b5b4-da6a2f6b5572)

**Comment by sleepingdragoninn** [comment]
hmm, is this achieved with a modrinth pack? or a prism pack? happy to
integrate it if it's possible to put on modrinth (packwiz downloads work
fine for prism for ftb mods, which we use)

**Comment by AlkyoneAoide** [comment]
I went back and re-downloaded all my modpacks and more to be sure, seems like the only ones doing that were ones downloaded from the curseforge tab in prism and atlauncher, mothing from modrinth...  Sorry about that

**Comment by sleepingdragoninn** [comment]
no problem! thanks for checking it out
