### ISSUE TITLE
Ice doesn't melt during warm seasons 

### ISSUE THREAD

**Issue by MarioAndWeegee3** [HerrahStrings/packwiz-packs#27]
https://github.com/lucaargolo/fabric-seasons/issues/133

This is fixed in a more recent update of the seasons mod

**Comment by sleepingdragoninn** [comment]
We maintain a [fork](https://github.com/lucaargolo/fabric-seasons/compare/1.19..sisby-folk:fabric-seasons:1.19) of seasons to preserve world compatibility with pre-2.0 versions for TQuilt 1.19, along with removing the mod's default anti-features (fetching advertisements from a github gist every time you join a world)

Upstreamed and regenerated the configs. Should be good!
