### ISSUE TITLE
quilt-kotlin-libraries and fabric language kotlin , both needed yet they dont work with eachother

### ISSUE THREAD

**Issue by JustRad123** [HerrahStrings/packwiz-packs#29]
i have a mod which needs fabric language kotlin but the whole modpack that i use ( tinkers quilt plus 1.19.2) wont work without quilt kotlin libraries , the mod which doesnt work without kotlin is: Way2Way
used to see waypoints on Xaeros minimap/worldmap , i admire your modpacks  (tho i think those could be expanded upon and created many branches into few different mods )  and i understand you can just not have time. For now i will just not use the Way2Way mod but if  the issue could be resolved i'd be more than thankfull <3 

(also i apologise for my poor grammar)

also got a question cause its nowhere explained nor in the controls menu   how do i go to quests? also the mod for quests doesnt even seem to download when i download  tinkers quilt or tinkers quilt plus

**Comment by sleepingdragoninn** [comment]
QKL provides FLK, if a mod doesn't work, try a newer version of QKL if it's available, or an older version of the mod.

second issue is #24

**Comment by JustRad123** [comment]
> QKL provides FLK, if a mod doesn't work, try a newer version of QKL if it's available, or an older version of the mod.
> 
> second issue is #24

so if i download the quest mod the quests and all should be there ingame right?(ye it did , no need to reply ig )

also huge thanks for the help  , very apriciated
