### ISSUE TITLE
Inventory Tab issue

### ISSUE THREAD

**Issue by EXfighter** [HerrahStrings/packwiz-packs#30]
Running Tinkerers Quilt 4.2.0 (MC 1.20)

Inventory Tab looks to be overlapping with each other.
Not sure what is causing it or how to remedy.

<img width="264" alt="Screenshot 2024-03-26 at 14 02 44" src="https://github.com/sisby-folk/tinkerers-quilt/assets/72012692/949beab2-226b-4c3f-b5e2-4a21d53fcc2a">

**Comment by sleepingdragoninn** [comment]
looks like you have a leftover version of inventory tabs 0.x installed alongside 1.x - uninstall 0.x
