### ISSUE TITLE
(TQ+ 1.20 Edge) Falling leaves downloads as "null"

### ISSUE THREAD

**Issue by kapertdog** [HerrahStrings/packwiz-packs#31]
![04_20240415_233345](https://github.com/sisby-folk/tinkerers-quilt/assets/40202917/3e9620da-ad21-4cf7-9bb6-dc33ff418f44)
![04_20240415_233430](https://github.com/sisby-folk/tinkerers-quilt/assets/40202917/31cee3a2-719c-42af-ba60-10370a286dad)
![04_20240415_233715](https://github.com/sisby-folk/tinkerers-quilt/assets/40202917/6606c0ab-95d8-4c44-8306-f673b3cac646)
![04_20240415_234322](https://github.com/sisby-folk/tinkerers-quilt/assets/40202917/20aefa18-fd41-4ec9-a57b-e6e6bade30fa)

**Comment by sleepingdragoninn** [comment]
looks like we accidentally typed a commit message into the metafile for the mod :joy: fixed
![image](https://github.com/sisby-folk/tinkerers-quilt/assets/55819817/060f135b-3263-4090-81fb-515fdc417804)
