### ISSUE TITLE
[1.20 Modded Edge] Cabbage seeds don't compost consistently

### ISSUE THREAD

**Issue by Rytelus** [HerrahStrings/packwiz-packs#32]
Setup:
1. Use edge download on prism launcher
2. Move versions down for any mods that require newer versions on start

Glitch:
- Right-clicking on the composter does not work
- Hopper feeding into composter does not work
- Create chute is inconsistent (worked once and never again)
- Shows up on singleplayer and on a dedicated server (RIP my farm chest with several stacks of cabbage seeds)

**Comment by sleepingdragoninn** [comment]
I think you want https://modrinth.com/mod/farmers-delight-refabricated for this one unless it's already fixed in a new mod version.
