### ISSUE TITLE
(1.20 Edge) Dynamic FPS requires Quilt Loader >= 0.25.0 since 3.4.3

### ISSUE THREAD

**Issue by kapertdog** [HerrahStrings/packwiz-packs#33]
![%T_%Y%M%D_%H%m%S-38](https://github.com/sisby-folk/tinkerers-quilt/assets/40202917/2db3a628-db9e-4c4b-8c82-ca680555acce)

**Comment by sleepingdragoninn** [comment]
can't update the loader automatically ([unsup feature request](https://git.sleeping.town/unascribed/unsup/issues/11)) and updating the instance zip to resolve it is tedious for both us to do and users to apply - just update it yourself if this happens, bane of using an edge version.
