### ISSUE TITLE
What are your plans for Tinker's Quilt 1.19?

### ISSUE THREAD

**Issue by strawberry-kitten** [HerrahStrings/packwiz-packs#4]
I was just wondering what your plans are for 1.19

**Comment by sleepingdragoninn** [comment]
If the core mods of the pack get stable releases on 1.19.2, then we'll release a version there. Currently it's not even close ahah

**Comment by sleepingdragoninn** [comment]
Oh apologies for my hubris 
![image](https://user-images.githubusercontent.com/55819817/195339417-9c2bdda6-a2b9-4853-99bd-030db3ee02ef.png)

**Comment by sleepingdragoninn** [comment]
![javaw_u2K4n4jUrD](https://user-images.githubusercontent.com/55819817/195340480-887d9b24-f4aa-47ca-b9a6-172b1179287a.jpg)

Only down about 3 mods and one of them is ours - we'll look into replacements, update all our mods to use 1.19 properly, and get a release out once its tested.

**Comment by sleepingdragoninn** [comment]
[Now in testing!](https://sisby-folk.github.io/mc-packs/)

**Comment by sleepingdragoninn** [comment]
[Up on modrinth](https://modrinth.com/modpack/tinkerers-quilt/version/3.4.2%2B1.19)
