### ISSUE TITLE
TQuilt+ 1.19.2 Bugs [Infinidoge]

### ISSUE THREAD

**Issue by Infinidoge** [HerrahStrings/packwiz-packs#5]
- [x] Portable Crafting Standalone causes a crash upon pressing the crafting button (<https://mclo.gs/Fhfl5Oy>)
- [x] Portable Crafting Standalone's crash extends to anything which shows the Inventory Tabs, due to its integration (<https://mclo.gs/wBVMxYl>)

**Comment by sleepingdragoninn** [comment]
I'll leave this open so you can add any extras. Portable crafting stuff solved with portable crafting standalone 1.3.0+1.19
