### ISSUE TITLE
TQuilt+ 1.19.2 Stonecutter Crash

### ISSUE THREAD

**Issue by listerla** [HerrahStrings/packwiz-packs#7]
I'm not great at reading crash logs, so I can't tell what mod is the culprit or I'd have put this bug report upstream already. Upon using the stonecutter and picking up the results (stone bricks) the game instantly crashes. Server does not crash.

[crash-2022-11-23_18.29.53-client.txt](https://github.com/sisby-folk/mc-packs/files/10079762/crash-2022-11-23_18.29.53-client.txt)

**Comment by sleepingdragoninn** [comment]
Could be NBT crafting - I'll have a look into it.

**Comment by sleepingdragoninn** [comment]
Can't reproduce on 3.4.4 singleplayer: 
https://user-images.githubusercontent.com/55819817/203686053-8e6d1cd1-2b73-4e46-9c1a-e8fc5f28d1e9.mp4

or multiplayer: 
https://user-images.githubusercontent.com/55819817/203686307-3388eab9-ac5c-4f5a-bf89-1fc8fd1d61a2.mp4

if you update and the issue still occurs, please note any mods added to the pack, an d send your `logs/latest.log` after the crash.

**Comment by sleepingdragoninn** [comment]
Oh wait I missed the plus. One moment!

None of the plus/modded packs have really reached anything close to "beta" or "stable" just yet (I don't think 1.18 ever will), but 1.19.2 plus is looking like the strongest candidate - So I'm happy to accept issues like this.

**Comment by sleepingdragoninn** [comment]
Reproduced (inc. in singleplayer) - chances are it's [Consistency+](https://modrinth.com/mod/consistencyplus) or [ArchEx](https://modrinth.com/mod/arch-ex) - possibly in conflict with [NBT Crafting](https://modrinth.com/mod/nbt-crafting)

**Comment by sleepingdragoninn** [comment]
Confirmed occurs on this set
![image](https://user-images.githubusercontent.com/55819817/203687722-17907eed-630d-4e77-9d05-f1b8f819c060.png)

**Comment by sleepingdragoninn** [comment]
Confirmed a Consistency+ Issue - checking on fabric
![image](https://user-images.githubusercontent.com/55819817/203687911-23522d3a-b84d-479e-999b-ab6fd8935822.png)

**Comment by sleepingdragoninn** [comment]
Here it is! https://github.com/ConsistencyPlus/ConsistencyPlus/issues/137 hopefully a fix comes through soon enough.

**Comment by listerla** [comment]
Thank you for looking into it!

**Comment by listerla** [comment]
Occurring now on TQuilt Modded 1.19.2

[crash-2023-04-14_18.03.28-client.txt](https://github.com/sisby-folk/mc-packs/files/11237376/crash-2023-04-14_18.03.28-client.txt)

Note that obtaining stone bricks is impossible b/c recipe for sturdy stone overrides recipe for polished stone

**Comment by sleepingdragoninn** [comment]
still no update to consistency+ last we checked

they've been working on some kind of major update so the fix hasn't gone
out.

**Comment by listerla** [comment]
Oh, sorry! I assumed since their issue was closed this'd be a different one, but that makes sense.

**Comment by sleepingdragoninn** [comment]
Resolved! built the mod at the fix commit from source, seems to work.
